# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'rspec-gc-control'
  s.version = '1.0.1meltwater'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.authors = ['Jon Frisby']
  s.date = '2012-08-12'
  s.description = 'Explicit control over garbage collection behavior for RSpec.'
  s.email = 'jfrisby@mrjoy.com'
  s.extra_rdoc_files = [
    'LICENSE',
    'README.md'
  ]
  s.files = [
    'CHANGELOG.md',
    'LICENSE',
    'README.md',
    'lib/rspec-gc-control.rb',
    'lib/rspec-gc-control/base_text_formatter.rb',
    'lib/rspec-gc-control/configuration.rb',
    'lib/rspec-gc-control/example.rb',
    'rspec-gc-control.gemspec'
  ]
  s.homepage = 'http://github.com/MrJoy/rspec-gc-control'
  s.licenses = ['MIT']
  s.require_paths = ['lib']
  s.rubygems_version = '2.6.6'
  s.summary = 'Explicit control over garbage collection behavior for RSpec.'
  s.specification_version = 3
  s.add_runtime_dependency(%q<rspec-core>, ['>= 3.0.0'])
end
